project_id = "dtqyyvjosdgoqloxybnx"

[functions.create-visitor]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.generate-certificates]
verify_jwt = true

[functions.send-certificate-emails]
verify_jwt = true

[functions.resend-webhook]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.create-member-registration]
verify_jwt = false

[functions.self-attendance]
verify_jwt = false

[functions.event-pre-register-lookup]
verify_jwt = false

[functions.event-pre-register]
verify_jwt = false

[functions.event-special-register]
verify_jwt = false

[functions.fundraising-lookup]
verify_jwt = false

[functions.fundraising-public-pledge]
verify_jwt = false

[functions.fundraising-public-donate]
verify_jwt = false



[functions.backfill-auth-users]
verify_jwt = true

[functions.provision-auth-user]
verify_jwt = true
