const LANGUAGE_STORAGE_KEY = 'user-language-preference';

export type SupportedLanguage = 'en' | 'fr';

export function detectBrowserLanguage(): SupportedLanguage {
  // Check localStorage first for cached preference
  const cached = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (cached === 'fr' || cached === 'en') {
    return cached as SupportedLanguage;
  }

  // Detect from browser
  const browserLang = navigator.language || (navigator as any).userLanguage;
  const langCode = browserLang.toLowerCase().split('-')[0];
  
  const language: SupportedLanguage = langCode === 'fr' ? 'fr' : 'en';
  
  // Cache the detected language
  localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  
  return language;
}

export function setLanguagePreference(language: SupportedLanguage) {
  localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
}

export function getLocalizedField<T>(
  englishValue: T | null | undefined,
  frenchValue: T | null | undefined,
  language: SupportedLanguage
): T | null | undefined {
  if (language === 'fr' && frenchValue) {
    return frenchValue;
  }
  return englishValue;
}

// UI translations
export const translations = {
  en: {
    aboutEvent: "About This Event",
    meetSpeakers: "Meet Our Speakers",
    testimonials: "What Attendees Say",
    faq: "Frequently Asked Questions",
    faqSubtitle: "Find answers to common questions about the event",
    registerEvent: "Register for Event",
    contactUs: "Contact Us",
    date: "Date",
    time: "Time",
    location: "Location",
    capacity: "Capacity",
    availability: "Availability",
    spotsAvailable: "spots available",
    eventFull: "Event Full",
    cost: "Cost",
    free: "Free",
    organizer: "Organizer",
    requirements: "Requirements",
    relatedEvents: "Related Events",
    viewDetails: "View Details",
    today: "Today",
    upcoming: "Upcoming",
    pastEvent: "Past Event",
    completed: "Completed",
    cancelled: "Cancelled",
    featured: "Featured",
    people: "people",
    unlimited: "Unlimited",
    readyToJoin: "Ready to Join?",
    reserveSpot: "Reserve your spot today and be part of something extraordinary",
    eventCost: "Event Cost",
    registerForEvent: "Register",
    whatsappNotAvailable: "WhatsApp contact not available for this event",
    eventCompleted: "Event Completed",
    registrationUnavailable: "Registration Unavailable",
    eventCompletedDesc: "This event has already taken place. Check out our upcoming events!",
    registrationUnavailableDesc: "Registration is currently not available for this event.",
    viewAllEvents: "View All Events",
    eventNotFound: "Event Not Found",
    eventNotFoundDesc: "We couldn't find the event you're looking for.",
    backToEvents: "← Back to Events",
    eventGallery: "Event Gallery",
    eventGalleryDescription: "Take a look at what makes this event special",
    testimonialsDescription: "Hear from those who've experienced our events",
    footerMission: "Building a network of fellowships that are spiritually, intellectually and economically empowered to transform lives.",
    // Visitor Registration Page
    visitorRegTitle: "VIP Registration Form",
    visitorRegDescription: "Welcome to WCA, a place where impact leaders are made.",
    welcomeTo: "Welcome to",
    firstName: "First Name",
    lastName: "Last Name",
    emailAddress: "Email Address",
    phone: "Phone",
    phoneNumber: "Phone Number",
    phoneDescription: "This number will be used for calls, SMS, and WhatsApp communication",
    address: "Address",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    selectGender: "Select gender",
    male: "Male",
    female: "Female",
    occupation: "Occupation",
    emergencyContact: "Emergency Contact",
    emergencyContactName: "Emergency Contact Name",
    emergencyContactPhone: "Emergency Contact Phone",
    completeRegistration: "Submit Registration",
    alreadyMember: "Already a member?",
    signIn: "Sign In",
    back: "Back",
    regionNotFound: "Region Not Found",
    regionNotFoundDesc: "The region you're trying to register for could not be found.",
    returnToHome: "Return to Home",
    registrationSuccessful: "Registration Successful!",
    yourVisitorId: "Your Visitor ID",
    saveIdMessage: "Please save this ID for your records. A regional administrator will contact you soon.",
    backToRegionalPage: "Back to Regional Page",
    registerAgain: "Register Again",
    registrationFailed: "Registration failed. Please try again.",
    vipWelcomeMessage: "Welcome! You have been registered as a WCA VIP Visitor.",
    registerAnotherVisitor: "Register Another Visitor",
    selectEvent: "Which event did you attend?",
    selectEventPlaceholder: "Choose an event",
    optional: "Optional",
    eventSatisfaction: "How satisfied are you with this event on a scale of 1 - 5 ?",
    referralSource: "How did you hear about us?",
    selectReferralSource: "Select an option",
    socialMedia: "Social Media",
    website: "Website",
    invitedBy: "Invited by someone",
    other: "Other",
    referralPersonName: "Who invited you?",
    enterPersonName: "Enter the person's name",
    referralOtherDetails: "Please explain",
    explainReferralSource: "Tell us how you heard about us",
    // Member Registration
    memberRegistration: "Member Registration",
    memberWelcome: "Welcome! Register as a new member",
    personalInformation: "Personal Information",
    whatsappNumber: "WhatsApp Number",
    whatsappDescription: "Your WhatsApp number for easy communication",
    spiritualInformation: "Spiritual Information",
    foundationSchool: "Have you gone through Foundation School?",
    foundationSchoolDate: "Foundation School Completion Date",
    haveBaptized: "Have you been baptized?",
    baptismDate: "Baptism Date",
    selectAnswer: "Select an answer",
    yes: "Yes",
    no: "No",
    pickDate: "Pick a date",
    ministryService: "Ministry & Service",
    ministryInterests: "Ministry Interests",
    ministryInterestsDescription: "Select all areas where you'd like to serve",
    skillsTalents: "Skills & Talents",
    skillsTalentsPlaceholder: "Describe your skills, talents, and experience that you can use to serve...",
    skillsTalentsDescription: "Help us understand how you can contribute to the ministry",
    dcgSelection: "DCG Selection",
    selectDcg: "Select Your DCG",
    selectDcgPlaceholder: "Choose a DCG (optional)",
    dcgDescription: "Join a Discipleship Community Group to grow together",
    memberRegistrationSuccess: "Member Registration Successful!",
    yourLoginCredentials: "Your Login Credentials",
    email: "Email",
    password: "Password",
    pleaseChangePassword: "Please change your password after your first login",
    loginNow: "Login Now",
    registerAnother: "Register Another Member",
    invalidRegionCode: "The region code you provided is invalid",
    backToHome: "Back to Home",
    // Navigation & Layout
    home: "Home",
    aboutUs: "About Us",
    locations: "Locations",
    events: "Events",
    resources: "Resources",
    visitUs: "Visit Us",
    language: "Language",
    quickLinks: "Quick Links",
    mediaSermons: "Media & Sermons",
    storeLibrary: "Store/Library",
    newsBlog: "News & Blog",
    counselling: "Counselling",
    fundraising: "Fundraising",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    visitorRegistration: "Visitor Registration",
    ourLocations: "Our Locations",
    // Homepage
    upcomingEvents: "Upcoming Events",
    learnMore: "Learn More",
    storiesOfTransformation: "Stories of Transformation",
    stayUpdated: "Stay Updated",
    subscribe: "Subscribe",
    multiDay: "Multi-day",
    noFeaturedEvents: "No featured events at the moment. Check back soon!",
    weRespectPrivacy: "We respect your privacy. Unsubscribe at any time.",
    // Locations Page
    globalNetwork: "Global Network",
    discoverSpiritualHome: "Discover Your Spiritual Home",
    locationHeroSubtitle: "Connect with vibrant communities across the globe. Find WCA Centers and DCG Homes where faith, fellowship, and transformation happen daily.",
    findYourCommunity: "Find Your Community",
    searchLocations: "Search by name, city, or region...",
    allLocations: "All Locations",
    wcaCenters: "WCA Centers",
    dcgHomes: "DCG Homes",
    allRegions: "All Regions",
    clearFilters: "Clear filters",
    locationsFound: "locations found",
    noLocationsFound: "No locations found",
    dontSeeYourArea: "Don't See Your Area?",
    startConversation: "Start the Conversation",
    exploreEvents: "Explore Events",
    ourGlobalLocations: "Our Global Locations",
    showingLocations: "Showing",
    ofLocations: "of",
    weAreExpanding: "We're expanding our global network every day. Contact us to learn about upcoming locations or discover how to bring WCA to your community.",
    // Events Page
    eventsCalendar: "Events Calendar",
    upcomingWcaEvents: "Upcoming WCA Events",
    searchEvents: "Search events...",
    showFilters: "Show Filters",
    hideFilters: "Hide Filters",
    noEventsFound: "No events found",
    organizeEvent: "Organize an Event with WCA",
    organizeEventDesc: "Are you interested in hosting a WCA event in your area? We provide resources and support to help you organize impactful gatherings for your community.",
    findALocation: "Find a Location",
    // Blog Page
    newsBlogTitle: "News & Blog",
    blogPageDesc: "Stay updated with the latest news, testimonies, and articles from the World Changers Association.",
    all: "All",
    news: "News",
    testimonies: "Testimonies",
    articles: "Articles",
    featuredPosts: "Featured Posts",
    searchPosts: "Search posts...",
    readMore: "Read More",
    comments: "comments",
    // Counseling Page
    counselingServices: "Counseling Services",
    counselingDesc: "Our team of licensed counselors and pastoral staff are here to provide guidance, support, and biblical wisdom for life's challenges.",
    searchCounselors: "Search counselors...",
    allSpecialties: "All Specialties",
    allDays: "All Days",
    viewProfileSchedule: "View Profile & Schedule",
    counselorProfile: "Counselor Profile",
    specialties: "Specialties",
    languagesSpoken: "Languages",
    experience: "Experience",
    about: "About",
    selectTimeSlot: "Select a Time Slot",
    scheduleAppointment: "Schedule Appointment",
    requestAppointment: "Request Appointment",
    // Fundraising Page
    fundraisingProjects: "Fundraising Projects",
    fundraisingDesc: "Join us in making a difference through these important initiatives that are transforming lives and communities.",
    searchProjects: "Search projects...",
    allCategories: "All Categories",
    allProjects: "All Projects",
    active: "Active",
    goalAmount: "Goal",
    raised: "Raised",
    supporters: "Supporters",
    startDate: "Start Date",
    endDate: "End Date",
    donate: "Donate",
    donateNow: "Donate Now",
    projectUpdates: "Project Updates",
    selectAmount: "Select Amount",
    customAmount: "Custom Amount",
    // Media Page
    mediaAndSermons: "Media & Sermons",
    mediaDesc: "Access our library of sermons, event recordings, and teachings to grow in your spiritual journey.",
    sermons: "Sermons",
    category: "Category",
    // Store Page
    wcaStore: "WCA Store",
    library: "Library",
    storeDesc: "Browse our collection of books, courses, and merchandise to support your spiritual journey.",
    libraryDesc: "Borrow resources from our extensive library to enrich your knowledge and growth.",
    featuredCollection: "Featured Collection",
    newArrivals: "New Arrivals",
    bestseller: "Bestseller",
    addToCart: "Add to Cart",
    filters: "Filters",
    categories: "Categories",
    type: "Type",
    book: "Book",
    merchandise: "Merchandise",
    audio: "Audio",
    course: "Course",
    // Already Enrolled (Duplicate Visitor/Member)
    welcomeBack: "Welcome Back!",
    alreadyRegisteredAsVisitor: "You're already registered as a visitor in this region. No need to register again!",
    alreadyRegisteredAsMember: "You're already registered as a member in this region. No need to register as a visitor!",
    alreadyRegisteredMessage: "You're already registered in this region.",
    yourMemberId: "Your Member ID",
    goToHomepage: "Go to Homepage",
    tryDifferentEmail: "Try Different Email",
  },
  fr: {
    aboutEvent: "À propos de cet événement",
    meetSpeakers: "Rencontrez nos conférenciers",
    testimonials: "Ce que disent les participants",
    faq: "Questions fréquemment posées",
    faqSubtitle: "Trouvez des réponses aux questions courantes sur l'événement",
    registerEvent: "S'inscrire à l'événement",
    contactUs: "Nous contacter",
    date: "Date",
    time: "Heure",
    location: "Lieu",
    capacity: "Capacité",
    availability: "Disponibilité",
    spotsAvailable: "places disponibles",
    eventFull: "Événement complet",
    cost: "Coût",
    free: "Gratuit",
    organizer: "Organisateur",
    requirements: "Exigences",
    relatedEvents: "Événements connexes",
    viewDetails: "Voir les détails",
    today: "Aujourd'hui",
    upcoming: "À venir",
    pastEvent: "Événement passé",
    completed: "Terminé",
    cancelled: "Annulé",
    featured: "En vedette",
    people: "personnes",
    unlimited: "Illimité",
    readyToJoin: "Prêt à vous joindre?",
    reserveSpot: "Réservez votre place aujourd'hui et faites partie de quelque chose d'extraordinaire",
    eventCost: "Coût de l'événement",
    registerForEvent: "S'inscrire",
    whatsappNotAvailable: "Contact WhatsApp non disponible pour cet événement",
    eventCompleted: "Événement terminé",
    registrationUnavailable: "Inscription indisponible",
    eventCompletedDesc: "Cet événement a déjà eu lieu. Consultez nos événements à venir!",
    registrationUnavailableDesc: "L'inscription n'est actuellement pas disponible pour cet événement.",
    viewAllEvents: "Voir tous les événements",
    eventNotFound: "Événement introuvable",
    eventNotFoundDesc: "Nous n'avons pas pu trouver l'événement que vous recherchez.",
    backToEvents: "← Retour aux événements",
    eventGallery: "Galerie de l'événement",
    eventGalleryDescription: "Découvrez ce qui rend cet événement spécial",
    testimonialsDescription: "Écoutez ceux qui ont vécu nos événements",
    footerMission: "Construire un réseau de communautés spirituellement, intellectuellement et économiquement habilitées à transformer des vies.",
    // Visitor Registration Page
    visitorRegTitle: "Formulaire d'inscription VIP",
    visitorRegDescription: "Bienvenue à WCA, un endroit où les leaders d'impact sont formés.",
    welcomeTo: "Bienvenue à",
    firstName: "Prénom",
    lastName: "Nom de famille",
    emailAddress: "Adresse e-mail",
    phone: "Téléphone",
    phoneNumber: "Numéro de téléphone",
    phoneDescription: "Ce numéro sera utilisé pour les appels, SMS et WhatsApp",
    address: "Adresse",
    dateOfBirth: "Date de naissance",
    gender: "Sexe",
    selectGender: "Sélectionnez le sexe",
    male: "Masculin",
    female: "Féminin",
    occupation: "Profession",
    emergencyContact: "Contact d'urgence",
    emergencyContactName: "Nom du contact d'urgence",
    emergencyContactPhone: "Téléphone du contact d'urgence",
    completeRegistration: "Soumettre l'inscription",
    alreadyMember: "Déjà membre?",
    signIn: "Se connecter",
    back: "Retour",
    regionNotFound: "Région introuvable",
    regionNotFoundDesc: "La région pour laquelle vous essayez de vous inscrire est introuvable.",
    returnToHome: "Retour à l'accueil",
    registrationSuccessful: "Inscription réussie!",
    yourVisitorId: "Votre ID de visiteur",
    saveIdMessage: "Veuillez conserver cet identifiant pour vos dossiers. Un administrateur régional vous contactera bientôt.",
    backToRegionalPage: "Retour à la page régionale",
    registerAgain: "S'inscrire à nouveau",
    registrationFailed: "L'inscription a échoué. Veuillez réessayer.",
    vipWelcomeMessage: "Bienvenue! Vous avez été enregistré en tant que visiteur VIP WCA.",
    registerAnotherVisitor: "Enregistrer un autre visiteur",
    selectEvent: "Quel événement avez-vous assisté ?",
    selectEventPlaceholder: "Choisissez un événement",
    optional: "Optionnel",
    eventSatisfaction: "Quel est votre niveau de satisfaction pour cet événement sur une échelle de 1 à 5 ?",
    referralSource: "Comment avez-vous entendu parler de nous ?",
    selectReferralSource: "Sélectionnez une option",
    socialMedia: "Réseaux sociaux",
    website: "Site web",
    invitedBy: "Invité par quelqu'un",
    other: "Autre",
    referralPersonName: "Qui vous a invité ?",
    enterPersonName: "Entrez le nom de la personne",
    referralOtherDetails: "Veuillez expliquer",
    explainReferralSource: "Dites-nous comment vous avez entendu parler de nous",
    // Member Registration
    memberRegistration: "Inscription des membres",
    memberWelcome: "Bienvenue! Inscrivez-vous en tant que nouveau membre",
    personalInformation: "Informations personnelles",
    whatsappNumber: "Numéro WhatsApp",
    whatsappDescription: "Votre numéro WhatsApp pour une communication facile",
    spiritualInformation: "Informations spirituelles",
    foundationSchool: "Avez-vous suivi l'École de Fondation ?",
    foundationSchoolDate: "Date d'achèvement de l'École de Fondation",
    haveBaptized: "Avez-vous été baptisé?",
    baptismDate: "Date de baptême",
    selectAnswer: "Sélectionnez une réponse",
    yes: "Oui",
    no: "Non",
    pickDate: "Choisir une date",
    ministryService: "Ministère et service",
    ministryInterests: "Intérêts ministériels",
    ministryInterestsDescription: "Sélectionnez tous les domaines où vous aimeriez servir",
    skillsTalents: "Compétences et talents",
    skillsTalentsPlaceholder: "Décrivez vos compétences, talents et expériences que vous pouvez utiliser pour servir...",
    skillsTalentsDescription: "Aidez-nous à comprendre comment vous pouvez contribuer au ministère",
    dcgSelection: "Sélection du DCG",
    selectDcg: "Sélectionnez votre DCG",
    selectDcgPlaceholder: "Choisissez un DCG (optionnel)",
    dcgDescription: "Rejoignez un groupe communautaire de discipulat pour grandir ensemble",
    memberRegistrationSuccess: "Inscription du membre réussie!",
    yourLoginCredentials: "Vos identifiants de connexion",
    email: "E-mail",
    password: "Mot de passe",
    pleaseChangePassword: "Veuillez changer votre mot de passe après votre première connexion",
    loginNow: "Se connecter maintenant",
    registerAnother: "Inscrire un autre membre",
    invalidRegionCode: "Le code de région que vous avez fourni n'est pas valide",
    backToHome: "Retour à l'accueil",
    // Navigation & Layout
    home: "Accueil",
    aboutUs: "À propos",
    locations: "Emplacements",
    events: "Événements",
    resources: "Ressources",
    visitUs: "Visitez-nous",
    language: "Langue",
    quickLinks: "Liens rapides",
    mediaSermons: "Médias et sermons",
    storeLibrary: "Boutique/Bibliothèque",
    newsBlog: "Actualités et blog",
    counselling: "Conseil",
    fundraising: "Collecte de fonds",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    visitorRegistration: "Inscription des visiteurs",
    ourLocations: "Nos emplacements",
    // Homepage
    upcomingEvents: "Événements à venir",
    learnMore: "En savoir plus",
    storiesOfTransformation: "Histoires de transformation",
    stayUpdated: "Restez informé",
    subscribe: "S'abonner",
    multiDay: "Multi-jours",
    noFeaturedEvents: "Aucun événement vedette pour le moment. Revenez bientôt!",
    weRespectPrivacy: "Nous respectons votre vie privée. Désabonnez-vous à tout moment.",
    // Locations Page
    globalNetwork: "Réseau mondial",
    discoverSpiritualHome: "Découvrez votre foyer spirituel",
    locationHeroSubtitle: "Connectez-vous avec des communautés dynamiques à travers le monde. Trouvez des centres WCA et des foyers DCG où la foi, la communion et la transformation se produisent quotidiennement.",
    findYourCommunity: "Trouvez votre communauté",
    searchLocations: "Rechercher par nom, ville ou région...",
    allLocations: "Tous les emplacements",
    wcaCenters: "Centres WCA",
    dcgHomes: "Foyers DCG",
    allRegions: "Toutes les régions",
    clearFilters: "Effacer les filtres",
    locationsFound: "emplacements trouvés",
    noLocationsFound: "Aucun emplacement trouvé",
    dontSeeYourArea: "Vous ne voyez pas votre région?",
    startConversation: "Commencer la conversation",
    exploreEvents: "Explorer les événements",
    ourGlobalLocations: "Nos emplacements mondiaux",
    showingLocations: "Affichage de",
    ofLocations: "sur",
    weAreExpanding: "Nous élargissons notre réseau mondial chaque jour. Contactez-nous pour en savoir plus sur les prochains emplacements ou découvrez comment amener WCA dans votre communauté.",
    // Events Page
    eventsCalendar: "Calendrier des événements",
    upcomingWcaEvents: "Événements WCA à venir",
    searchEvents: "Rechercher des événements...",
    showFilters: "Afficher les filtres",
    hideFilters: "Masquer les filtres",
    noEventsFound: "Aucun événement trouvé",
    organizeEvent: "Organiser un événement avec WCA",
    organizeEventDesc: "Êtes-vous intéressé à organiser un événement WCA dans votre région? Nous fournissons des ressources et un soutien pour vous aider à organiser des rassemblements marquants pour votre communauté.",
    findALocation: "Trouver un emplacement",
    // Blog Page
    newsBlogTitle: "Actualités et blog",
    blogPageDesc: "Restez informé des dernières nouvelles, témoignages et articles de la World Changers Association.",
    all: "Tout",
    news: "Actualités",
    testimonies: "Témoignages",
    articles: "Articles",
    featuredPosts: "Articles en vedette",
    searchPosts: "Rechercher des articles...",
    readMore: "Lire la suite",
    comments: "commentaires",
    // Counseling Page
    counselingServices: "Services de conseil",
    counselingDesc: "Notre équipe de conseillers agréés et de personnel pastoral est là pour fournir des conseils, un soutien et une sagesse biblique pour les défis de la vie.",
    searchCounselors: "Rechercher des conseillers...",
    allSpecialties: "Toutes les spécialités",
    allDays: "Tous les jours",
    viewProfileSchedule: "Voir le profil et l'horaire",
    counselorProfile: "Profil du conseiller",
    specialties: "Spécialités",
    languagesSpoken: "Langues",
    experience: "Expérience",
    about: "À propos",
    selectTimeSlot: "Sélectionner un créneau horaire",
    scheduleAppointment: "Planifier un rendez-vous",
    requestAppointment: "Demander un rendez-vous",
    // Fundraising Page
    fundraisingProjects: "Projets de collecte de fonds",
    fundraisingDesc: "Rejoignez-nous pour faire la différence grâce à ces initiatives importantes qui transforment des vies et des communautés.",
    searchProjects: "Rechercher des projets...",
    allCategories: "Toutes les catégories",
    allProjects: "Tous les projets",
    active: "Actif",
    goalAmount: "Objectif",
    raised: "Collecté",
    supporters: "Supporters",
    startDate: "Date de début",
    endDate: "Date de fin",
    donate: "Faire un don",
    donateNow: "Faire un don maintenant",
    projectUpdates: "Mises à jour du projet",
    selectAmount: "Sélectionner le montant",
    customAmount: "Montant personnalisé",
    // Media Page
    mediaAndSermons: "Médias et sermons",
    mediaDesc: "Accédez à notre bibliothèque de sermons, d'enregistrements d'événements et d'enseignements pour grandir dans votre parcours spirituel.",
    sermons: "Sermons",
    category: "Catégorie",
    // Store Page
    wcaStore: "Boutique WCA",
    library: "Bibliothèque",
    storeDesc: "Parcourez notre collection de livres, de cours et de marchandises pour soutenir votre parcours spirituel.",
    libraryDesc: "Empruntez des ressources de notre vaste bibliothèque pour enrichir vos connaissances et votre croissance.",
    featuredCollection: "Collection en vedette",
    newArrivals: "Nouveautés",
    bestseller: "Best-seller",
    addToCart: "Ajouter au panier",
    filters: "Filtres",
    categories: "Catégories",
    type: "Type",
    book: "Livre",
    merchandise: "Marchandise",
    audio: "Audio",
    course: "Cours",
    // Already Enrolled (Duplicate Visitor/Member)
    welcomeBack: "Bienvenue!",
    alreadyRegisteredAsVisitor: "Vous êtes déjà inscrit en tant que visiteur dans cette région. Pas besoin de vous réinscrire!",
    alreadyRegisteredAsMember: "Vous êtes déjà inscrit en tant que membre dans cette région. Pas besoin de vous inscrire comme visiteur!",
    alreadyRegisteredMessage: "Vous êtes déjà inscrit dans cette région.",
    yourMemberId: "Votre identifiant de membre",
    goToHomepage: "Aller à la page d'accueil",
    tryDifferentEmail: "Essayer un autre e-mail",
  },
};
