const LANGUAGE_STORAGE_KEY = 'user-language-preference';

export type SupportedLanguage = 'en' | 'fr';

export function detectBrowserLanguage(): SupportedLanguage {
  // Check localStorage first for cached preference
  const cached = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (cached === 'fr' || cached === 'en') {
    return cached as SupportedLanguage;
  }

  // Detect from browser
  const browserLang = navigator.language || (navigator as any).userLanguage;
  const langCode = browserLang.toLowerCase().split('-')[0];
  
  const language: SupportedLanguage = langCode === 'fr' ? 'fr' : 'en';
  
  // Cache the detected language
  localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  
  return language;
}

export function setLanguagePreference(language: SupportedLanguage) {
  localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
}

export function getLocalizedField<T>(
  englishValue: T | null | undefined,
  frenchValue: T | null | undefined,
  language: SupportedLanguage
): T | null | undefined {
  if (language === 'fr' && frenchValue) {
    return frenchValue;
  }
  return englishValue;
}

// UI translations
export const translations = {
  en: {
    aboutEvent: "About This Event",
    meetSpeakers: "Meet Our Speakers",
    testimonials: "What Attendees Say",
    faq: "Frequently Asked Questions",
    faqSubtitle: "Find answers to common questions about the event",
    registerEvent: "Register for Event",
    contactUs: "Contact Us",
    date: "Date",
    time: "Time",
    location: "Location",
    capacity: "Capacity",
    availability: "Availability",
    spotsAvailable: "spots available",
    eventFull: "Event Full",
    cost: "Cost",
    free: "Free",
    organizer: "Organizer",
    requirements: "Requirements",
    relatedEvents: "Related Events",
    viewDetails: "View Details",
    today: "Today",
    upcoming: "Upcoming",
    pastEvent: "Past Event",
    completed: "Completed",
    cancelled: "Cancelled",
    featured: "Featured",
    people: "people",
    unlimited: "Unlimited",
    readyToJoin: "Ready to Join?",
    reserveSpot: "Reserve your spot today and be part of something extraordinary",
    eventCost: "Event Cost",
    registerForEvent: "Register",
    whatsappNotAvailable: "WhatsApp contact not available for this event",
    eventCompleted: "Event Completed",
    registrationUnavailable: "Registration Unavailable",
    eventCompletedDesc: "This event has already taken place. Check out our upcoming events!",
    registrationUnavailableDesc: "Registration is currently not available for this event.",
    viewAllEvents: "View All Events",
    eventNotFound: "Event Not Found",
    eventNotFoundDesc: "We couldn't find the event you're looking for.",
    backToEvents: "← Back to Events",
    eventGallery: "Event Gallery",
    eventGalleryDescription: "Take a look at what makes this event special",
    testimonialsDescription: "Hear from those who've experienced our events",
    footerMission: "Building a network of fellowships that are spiritually, intellectually and economically empowered to transform lives.",
    // Visitor Registration Page
    visitorRegTitle: "VIP Registration Form",
    visitorRegDescription: "Welcome to WCA, a place where impact leaders are made.",
    welcomeTo: "Welcome to",
    firstName: "First Name",
    lastName: "Last Name",
    emailAddress: "Email Address",
    phone: "Phone",
    phoneNumber: "Phone Number",
    phoneDescription: "This number will be used for calls, SMS, and WhatsApp communication",
    address: "Address",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    selectGender: "Select gender",
    male: "Male",
    female: "Female",
    occupation: "Occupation",
    completeRegistration: "Submit Registration",
    alreadyMember: "Already a member?",
    signIn: "Sign In",
    back: "Back",
    regionNotFound: "Region Not Found",
    regionNotFoundDesc: "The region you're trying to register for could not be found.",
    returnToHome: "Return to Home",
    registrationSuccessful: "Registration Successful!",
    yourVisitorId: "Your Visitor ID",
    saveIdMessage: "Please save this ID for your records. A regional administrator will contact you soon.",
    backToRegionalPage: "Back to Regional Page",
    registerAgain: "Register Again",
    registrationFailed: "Registration failed. Please try again.",
    vipWelcomeMessage: "Welcome! You have been registered as a WCA VIP Visitor.",
    registerAnotherVisitor: "Register Another Visitor",
    selectEvent: "Which event did you attend?",
    selectEventPlaceholder: "Choose an event",
    optional: "Optional",
    eventSatisfaction: "How satisfied are you with this event on a scale of 1 - 5 ?",
    referralSource: "How did you hear about us?",
    selectReferralSource: "Select an option",
    socialMedia: "Social Media",
    website: "Website",
    invitedBy: "Invited by someone",
    other: "Other",
    referralPersonName: "Who invited you?",
    enterPersonName: "Enter the person's name",
    referralOtherDetails: "Please explain",
    joinInterest: "Would you like to join WCA?",
    joinYes: "Yes",
    joinNo: "No",
    joinUndecided: "Undecided",
    explainReferralSource: "Tell us how you heard about us",
    // Member Registration
    memberRegistration: "Member Registration",
    memberWelcome: "Welcome! Register as a new member",
    personalInformation: "Personal Information",
    whatsappNumber: "WhatsApp Number",
    whatsappDescription: "Your WhatsApp number for easy communication",
    spiritualInformation: "Spiritual Information",
    foundationSchool: "Have you gone through Foundation School?",
    foundationSchoolDate: "Foundation School Completion Date",
    haveBaptized: "Have you been baptized?",
    baptismDate: "Baptism Date",
    selectAnswer: "Select an answer",
    yes: "Yes",
    no: "No",
    pickDate: "Pick a date",
    ministryService: "Ministry & Service",
    ministryInterests: "Ministry Interests",
    ministryInterestsDescription: "Select all areas where you'd like to serve",
    skillsTalents: "Skills & Talents",
    skillsTalentsPlaceholder: "Describe your skills, talents, and experience that you can use to serve...",
    skillsTalentsDescription: "Help us understand how you can contribute to the ministry",
    dcgSelection: "DCG Selection",
    selectDcg: "Select Your DCG",
    selectDcgPlaceholder: "Choose a DCG (optional)",
    dcgDescription: "Join a Discipleship Community Group to grow together",
    memberRegistrationSuccess: "Member Registration Successful!",
    yourLoginCredentials: "Your Login Credentials",
    email: "Email",
    password: "Password",
    pleaseChangePassword: "Please change your password after your first login",
    loginNow: "Login Now",
    registerAnother: "Register Another Member",
    invalidRegionCode: "The region code you provided is invalid",
    backToHome: "Back to Home",
    // Navigation & Layout
    home: "Home",
    aboutUs: "About Us",
    locations: "Locations",
    events: "Events",
    resources: "Resources",
    visitUs: "Visit Us",
    language: "Language",
    quickLinks: "Quick Links",
    mediaSermons: "Media & Sermons",
    storeLibrary: "Store/Library",
    newsBlog: "News & Blog",
    counselling: "Counselling",
    fundraising: "Fundraising",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    visitorRegistration: "Visitor Registration",
    ourLocations: "Our Locations",
    // Homepage
    upcomingEvents: "Upcoming Events",
    learnMore: "Learn More",
    storiesOfTransformation: "Stories of Transformation",
    stayUpdated: "Stay Updated",
    subscribe: "Subscribe",
    multiDay: "Multi-day",
    noFeaturedEvents: "No featured events at the moment. Check back soon!",
    weRespectPrivacy: "We respect your privacy. Unsubscribe at any time.",
    // Locations Page
    globalNetwork: "Global Network",
    discoverSpiritualHome: "Discover Your Spiritual Home",
    locationHeroSubtitle: "Connect with vibrant communities across the globe. Find WCA Centers and DCG Homes where faith, fellowship, and transformation happen daily.",
    findYourCommunity: "Find Your Community",
    searchLocations: "Search by name, city, or region...",
    allLocations: "All Locations",
    wcaCenters: "WCA Centers",
    dcgHomes: "DCG Homes",
    allRegions: "All Regions",
    clearFilters: "Clear filters",
    locationsFound: "locations found",
    noLocationsFound: "No locations found",
    dontSeeYourArea: "Don't See Your Area?",
    startConversation: "Start the Conversation",
    exploreEvents: "Explore Events",
    ourGlobalLocations: "Our Global Locations",
    showingLocations: "Showing",
    ofLocations: "of",
    weAreExpanding: "We're expanding our global network every day. Contact us to learn about upcoming locations or discover how to bring WCA to your community.",
    // Events Page
    eventsCalendar: "Events Calendar",
    upcomingWcaEvents: "Upcoming WCA Events",
    searchEvents: "Search events...",
    showFilters: "Show Filters",
    hideFilters: "Hide Filters",
    noEventsFound: "No events found",
    organizeEvent: "Organize an Event with WCA",
    organizeEventDesc: "Are you interested in hosting a WCA event in your area? We provide resources and support to help you organize impactful gatherings for your community.",
    findALocation: "Find a Location",
    // Blog Page
    newsBlogTitle: "News & Blog",
    blogPageDesc: "Stay updated with the latest news, testimonies, and articles from the World Changers Association.",
    all: "All",
    news: "News",
    testimonies: "Testimonies",
    articles: "Articles",
    featuredPosts: "Featured Posts",
    searchPosts: "Search posts...",
    readMore: "Read More",
    comments: "comments",
    // Counseling Page
    counselingServices: "Counseling Services",
    counselingDesc: "Our team of licensed counselors and pastoral staff are here to provide guidance, support, and biblical wisdom for life's challenges.",
    searchCounselors: "Search counselors...",
    allSpecialties: "All Specialties",
    allDays: "All Days",
    viewProfileSchedule: "View Profile & Schedule",
    counselorProfile: "Counselor Profile",
    specialties: "Specialties",
    languagesSpoken: "Languages",
    experience: "Experience",
    about: "About",
    selectTimeSlot: "Select a Time Slot",
    scheduleAppointment: "Schedule Appointment",
    requestAppointment: "Request Appointment",
    // Fundraising Page
    fundraisingProjects: "Fundraising Projects",
    fundraisingDesc: "Join us in making a difference through these important initiatives that are transforming lives and communities.",
    searchProjects: "Search projects...",
    allCategories: "All Categories",
    allProjects: "All Projects",
    active: "Active",
    goalAmount: "Goal",
    raised: "Raised",
    supporters: "Supporters",
    startDate: "Start Date",
    endDate: "End Date",
    donate: "Donate",
    donateNow: "Donate Now",
    projectUpdates: "Project Updates",
    selectAmount: "Select Amount",
    customAmount: "Custom Amount",
    // Media Page
    mediaAndSermons: "Media & Sermons",
    mediaDesc: "Access our library of sermons, event recordings, and teachings to grow in your spiritual journey.",
    sermons: "Sermons",
    category: "Category",
    // Store Page
    wcaStore: "WCA Store",
    library: "Library",
    storeDesc: "Browse our collection of books, courses, and merchandise to support your spiritual journey.",
    libraryDesc: "Borrow resources from our extensive library to enrich your knowledge and growth.",
    featuredCollection: "Featured Collection",
    newArrivals: "New Arrivals",
    bestseller: "Bestseller",
    addToCart: "Add to Cart",
    filters: "Filters",
    categories: "Categories",
    type: "Type",
    book: "Book",
    merchandise: "Merchandise",
    audio: "Audio",
    course: "Course",
    // Already Enrolled (Duplicate Visitor/Member)
    welcomeBack: "Welcome Back!",
    alreadyRegisteredAsVisitor: "You're already registered as a visitor in this region. No need to register again!",
    alreadyRegisteredAsMember: "You're already registered as a member in this region. No need to register as a visitor!",
    alreadyRegisteredMessage: "You're already registered in this region.",
    yourMemberId: "Your Member ID",
    goToHomepage: "Go to Homepage",
    tryDifferentEmail: "Try Different Email",
    // Special Event Pre-Registration
    sr_badge: "Special Event Pre-Registration",
    sr_step_you: "You",
    sr_step_onboard: "Onboard",
    sr_step_family: "Family",
    sr_step_extras: "Extras",
    sr_identify_title: "Who is registering?",
    sr_identify_desc: "Enter the email or phone you used when you registered with WCA. If you're new, we'll get you onboarded right here.",
    sr_email: "Email",
    sr_telephone: "Telephone",
    sr_email_placeholder: "you@example.com",
    sr_phone_placeholder: "Phone number",
    sr_check: "Check",
    sr_hello_prefix: "Hello",
    sr_hello_middle: ", are you registering for",
    sr_hello_suffix: "as a family or an individual?",
    sr_individual: "Individual",
    sr_family_mode: "Family",
    sr_not_in_system: "We don't have you in the system yet. Click",
    sr_not_in_system_cta: "Continue",
    sr_not_in_system_tail: "to onboard and complete your registration.",
    sr_onboard_select_type_title: "Select the attendee type to register below.",
    sr_onboard_select_type_desc: "Pick the option that best fits this person.",
    sr_member_type: "Member",
    sr_visitor_type: "Visitor",
    sr_region_section: "WCA Region",
    sr_region_label: "Region",
    sr_region_placeholder: "Select your region",
    sr_region_help: "The WCA region you belong to or wish to be associated with.",
    sr_personal_info: "Personal Information",
    sr_family_name: "Family Name",
    sr_other_names: "Other Names",
    sr_phone: "Phone",
    sr_phone_placeholder_full: "+1 555 123 4567",
    sr_address: "Address",
    sr_address_placeholder: "Street, City, Country",
    sr_dob: "Date of birth",
    sr_gender: "Gender",
    sr_select_gender: "Select gender",
    sr_male: "Male",
    sr_female: "Female",
    sr_occupation: "Occupation",
    sr_select_occupation: "Select occupation",
    sr_spiritual_info: "Spiritual Information",
    sr_foundation_q: "Completed Foundation School?",
    sr_foundation_date: "Foundation School Date",
    sr_baptized_q: "Are you baptized?",
    sr_baptism_date: "Baptism Date",
    sr_select: "Select",
    sr_ministry_title: "Ministry & Service",
    sr_ministry_desc: "Select any ministries you're interested in serving.",
    sr_ministry_music: "Music & Worship",
    sr_ministry_teaching: "Teaching & Preaching",
    sr_ministry_youth: "Youth Ministry",
    sr_ministry_children: "Children's Ministry",
    sr_ministry_hospitality: "Hospitality",
    sr_ministry_media: "Media & Technology",
    sr_ministry_admin: "Administration",
    sr_ministry_counseling: "Counseling",
    sr_ministry_prayer: "Prayer Ministry",
    sr_ministry_outreach: "Outreach & Evangelism",
    sr_dcg_title: "Destiny Care Group",
    sr_dcg_label: "Select DCG",
    sr_dcg_select_placeholder: "Select a DCG",
    sr_dcg_select_region_first: "Select region first",
    sr_family_rel_title: "Family Relationships (Optional)",
    sr_rel_type: "Relationship Type",
    sr_select_rel: "Select relationship",
    sr_related_members: "Related Members",
    sr_search_members: "Search members…",
    sr_no_members: "No members found.",
    sr_add_rel: "Add relationship",
    sr_n_selected: "selected",
    sr_referral_title: "Referral",
    sr_referral_q: "How did you hear about us?",
    sr_select_referral: "Select referral source",
    sr_referral_invited_by: "Invited by someone",
    sr_referral_social_media: "Social media",
    sr_referral_website: "Website",
    sr_referral_other: "Other",
    sr_invited_by_members: "Member(s) who invited you",
    sr_relationship: "Relationship",
    sr_which_platform: "Which platform?",
    sr_select_platform: "Select platform",
    sr_platform_other: "Other",
    sr_tell_more: "Tell us more",
    sr_tell_more_placeholder: "How did you hear about us?",
    sr_interest_title: "Interest",
    sr_join_q: "Would you like to join WCA?",
    sr_yes: "Yes",
    sr_no: "No",
    sr_undecided: "Undecided",
    sr_rel_spouse: "Spouse",
    sr_rel_child: "Child",
    sr_rel_parent: "Parent",
    sr_rel_sibling: "Sibling",
    sr_rel_guardian: "Guardian",
    sr_rel_other: "Other",
    sr_family_section_title: "Family & Children",
    sr_family_section_desc: "Tick the family members joining you. You can also add someone new.",
    sr_your_family: "Your family",
    sr_child_badge: "child",
    sr_add_person: "Add person",
    sr_no_family: "No family added — that's fine if you're attending alone.",
    sr_linked: "Linked",
    sr_dont_have_person: "We don't have this person yet — onboard them here.",
    sr_lodging_title: "Lodging",
    sr_lodging_desc: "Let us know if you need accommodation arranged by the organizers.",
    sr_need_lodging: "I need lodging provided by the organizers",
    sr_days_attend: "Days you will attend",
    sr_health_title: "Allergies & Health Challenges",
    sr_health_desc: "Indicate any allergies or health challenges we should accommodate.",
    sr_health_food: "Food allergy",
    sr_health_drug: "Drug allergy",
    sr_health_asthma: "Asthma / Respiratory",
    sr_health_diabetes: "Diabetes",
    sr_health_hypertension: "Hypertension",
    sr_health_mobility: "Mobility / Accessibility",
    sr_health_other: "Other health/allergy",
    sr_other_health_placeholder: "Other health or allergy details",
    sr_pledge_title: "Pledge to support",
    sr_pledge_desc: "Optional — pledge an amount to help fund the event. We'll follow up to collect.",
    sr_fundraising_goal: "Fundraising goal",
    sr_continue: "Continue",
    sr_back: "Back",
    sr_submitting: "Submitting…",
    sr_confirm: "Confirm registration",
    sr_done_title: "You're registered!",
    sr_done_body_prefix: "Thank you for registering for",
    sr_done_body_suffix: ". You can start preparing to have a great time with the Lord.",
    sr_browse_other: "Browse other events",
    sr_event_unavailable_title: "Event not available",
    sr_event_unavailable_desc: "This event isn't open for special registration.",
    sr_back_to_events: "Back to events",
    sr_toast_success_prefix: "Registered",
    sr_toast_success_suffix: "attendee(s)!",
    sr_toast_error: "Could not complete registration",

    // Public fundraising
    fr_title: "Fundraising Projects",
    fr_subtitle: "Join us in making a difference through these important initiatives that are transforming lives and communities.",
    fr_search: "Search projects...",
    fr_all_status: "All Projects",
    fr_status_active: "Active",
    fr_status_completed: "Completed",
    fr_status_upcoming: "Upcoming",
    fr_no_projects: "No fundraising projects yet. Check back soon.",
    fr_details: "Details",
    fr_donate: "Donate",
    fr_pledge: "Pledge",
    fr_progress: "Progress",
    fr_supporters: "Supporters",
    fr_raised: "raised",
    fr_goal: "Goal",
    fr_about: "About this project",
    fr_recent_supporters: "Recent supporters",
    fr_no_supporters: "Be the first to support this project.",
    fr_anonymous: "Anonymous",
    fr_back: "Back",
    fr_pledge_title: "Take a pledge",
    fr_donate_title: "Make a donation",
    fr_phone: "Telephone number",
    fr_proceed: "Proceed",
    fr_checking: "Checking…",
    fr_greet_match: "Hello {name}, input your pledge amount below and confirm to send in your pledge.",
    fr_greet_match_donate: "Hello {name}, enter the amount you want to redeem now.",
    fr_greet_new: "Fill the form below and confirm to send in your pledge.",
    fr_greet_new_donate: "Fill the form below to make your donation.",
    fr_family_name: "Family Name",
    fr_other_names: "Other names",
    fr_email: "Email",
    fr_amount: "Amount",
    fr_pledge_amount: "Pledge amount",
    fr_note_optional: "Note (optional)",
    fr_confirm_pledge: "Confirm pledge",
    fr_pay_now: "Pay Now",
    fr_anonymous_toggle: "Donate anonymously",
    fr_my_pledge: "Your pledge",
    fr_pledged: "Pledged",
    fr_redeemed: "Redeemed",
    fr_remaining: "Remaining",
    fr_success_pledge: "Thank you! Your pledge has been recorded.",
    fr_success_donate: "Thank you! Your donation has been recorded and is awaiting payment.",
    fr_lookup_error: "Could not verify your number. Please try again.",
    fr_submit_error: "Something went wrong. Please try again.",
  },

  fr: {
    aboutEvent: "À propos de cet événement",
    meetSpeakers: "Rencontrez nos conférenciers",
    testimonials: "Ce que disent les participants",
    faq: "Questions fréquemment posées",
    faqSubtitle: "Trouvez des réponses aux questions courantes sur l'événement",
    registerEvent: "S'inscrire à l'événement",
    contactUs: "Nous contacter",
    date: "Date",
    time: "Heure",
    location: "Lieu",
    capacity: "Capacité",
    availability: "Disponibilité",
    spotsAvailable: "places disponibles",
    eventFull: "Événement complet",
    cost: "Coût",
    free: "Gratuit",
    organizer: "Organisateur",
    requirements: "Exigences",
    relatedEvents: "Événements connexes",
    viewDetails: "Voir les détails",
    today: "Aujourd'hui",
    upcoming: "À venir",
    pastEvent: "Événement passé",
    completed: "Terminé",
    cancelled: "Annulé",
    featured: "En vedette",
    people: "personnes",
    unlimited: "Illimité",
    readyToJoin: "Prêt à vous joindre?",
    reserveSpot: "Réservez votre place aujourd'hui et faites partie de quelque chose d'extraordinaire",
    eventCost: "Coût de l'événement",
    registerForEvent: "S'inscrire",
    whatsappNotAvailable: "Contact WhatsApp non disponible pour cet événement",
    eventCompleted: "Événement terminé",
    registrationUnavailable: "Inscription indisponible",
    eventCompletedDesc: "Cet événement a déjà eu lieu. Consultez nos événements à venir!",
    registrationUnavailableDesc: "L'inscription n'est actuellement pas disponible pour cet événement.",
    viewAllEvents: "Voir tous les événements",
    eventNotFound: "Événement introuvable",
    eventNotFoundDesc: "Nous n'avons pas pu trouver l'événement que vous recherchez.",
    backToEvents: "← Retour aux événements",
    eventGallery: "Galerie de l'événement",
    eventGalleryDescription: "Découvrez ce qui rend cet événement spécial",
    testimonialsDescription: "Écoutez ceux qui ont vécu nos événements",
    footerMission: "Construire un réseau de communautés spirituellement, intellectuellement et économiquement habilitées à transformer des vies.",
    // Visitor Registration Page
    visitorRegTitle: "Formulaire d'inscription VIP",
    visitorRegDescription: "Bienvenue à WCA, un endroit où les leaders d'impact sont formés.",
    welcomeTo: "Bienvenue à",
    firstName: "Prénom",
    lastName: "Nom de famille",
    emailAddress: "Adresse e-mail",
    phone: "Téléphone",
    phoneNumber: "Numéro de téléphone",
    phoneDescription: "Ce numéro sera utilisé pour les appels, SMS et WhatsApp",
    address: "Adresse",
    dateOfBirth: "Date de naissance",
    gender: "Sexe",
    selectGender: "Sélectionnez le sexe",
    male: "Masculin",
    female: "Féminin",
    occupation: "Profession",
    completeRegistration: "Soumettre l'inscription",
    alreadyMember: "Déjà membre?",
    signIn: "Se connecter",
    back: "Retour",
    regionNotFound: "Région introuvable",
    regionNotFoundDesc: "La région pour laquelle vous essayez de vous inscrire est introuvable.",
    returnToHome: "Retour à l'accueil",
    registrationSuccessful: "Inscription réussie!",
    yourVisitorId: "Votre ID de visiteur",
    saveIdMessage: "Veuillez conserver cet identifiant pour vos dossiers. Un administrateur régional vous contactera bientôt.",
    backToRegionalPage: "Retour à la page régionale",
    registerAgain: "S'inscrire à nouveau",
    registrationFailed: "L'inscription a échoué. Veuillez réessayer.",
    vipWelcomeMessage: "Bienvenue! Vous avez été enregistré en tant que visiteur VIP WCA.",
    registerAnotherVisitor: "Enregistrer un autre visiteur",
    selectEvent: "Quel événement avez-vous assisté ?",
    selectEventPlaceholder: "Choisissez un événement",
    optional: "Optionnel",
    eventSatisfaction: "Quel est votre niveau de satisfaction pour cet événement sur une échelle de 1 à 5 ?",
    referralSource: "Comment avez-vous entendu parler de nous ?",
    selectReferralSource: "Sélectionnez une option",
    socialMedia: "Réseaux sociaux",
    website: "Site web",
    invitedBy: "Invité par quelqu'un",
    other: "Autre",
    referralPersonName: "Qui vous a invité ?",
    enterPersonName: "Entrez le nom de la personne",
    referralOtherDetails: "Veuillez expliquer",
    joinInterest: "Souhaitez-vous rejoindre WCA ?",
    joinYes: "Oui",
    joinNo: "Non",
    joinUndecided: "Indécis",
    explainReferralSource: "Dites-nous comment vous avez entendu parler de nous",
    // Member Registration
    memberRegistration: "Inscription des membres",
    memberWelcome: "Bienvenue! Inscrivez-vous en tant que nouveau membre",
    personalInformation: "Informations personnelles",
    whatsappNumber: "Numéro WhatsApp",
    whatsappDescription: "Votre numéro WhatsApp pour une communication facile",
    spiritualInformation: "Informations spirituelles",
    foundationSchool: "Avez-vous suivi l'École de Fondation ?",
    foundationSchoolDate: "Date d'achèvement de l'École de Fondation",
    haveBaptized: "Avez-vous été baptisé?",
    baptismDate: "Date de baptême",
    selectAnswer: "Sélectionnez une réponse",
    yes: "Oui",
    no: "Non",
    pickDate: "Choisir une date",
    ministryService: "Ministère et service",
    ministryInterests: "Intérêts ministériels",
    ministryInterestsDescription: "Sélectionnez tous les domaines où vous aimeriez servir",
    skillsTalents: "Compétences et talents",
    skillsTalentsPlaceholder: "Décrivez vos compétences, talents et expériences que vous pouvez utiliser pour servir...",
    skillsTalentsDescription: "Aidez-nous à comprendre comment vous pouvez contribuer au ministère",
    dcgSelection: "Sélection du DCG",
    selectDcg: "Sélectionnez votre DCG",
    selectDcgPlaceholder: "Choisissez un DCG (optionnel)",
    dcgDescription: "Rejoignez un groupe communautaire de discipulat pour grandir ensemble",
    memberRegistrationSuccess: "Inscription du membre réussie!",
    yourLoginCredentials: "Vos identifiants de connexion",
    email: "E-mail",
    password: "Mot de passe",
    pleaseChangePassword: "Veuillez changer votre mot de passe après votre première connexion",
    loginNow: "Se connecter maintenant",
    registerAnother: "Inscrire un autre membre",
    invalidRegionCode: "Le code de région que vous avez fourni n'est pas valide",
    backToHome: "Retour à l'accueil",
    // Navigation & Layout
    home: "Accueil",
    aboutUs: "À propos",
    locations: "Emplacements",
    events: "Événements",
    resources: "Ressources",
    visitUs: "Visitez-nous",
    language: "Langue",
    quickLinks: "Liens rapides",
    mediaSermons: "Médias et sermons",
    storeLibrary: "Boutique/Bibliothèque",
    newsBlog: "Actualités et blog",
    counselling: "Conseil",
    fundraising: "Collecte de fonds",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    visitorRegistration: "Inscription des visiteurs",
    ourLocations: "Nos emplacements",
    // Homepage
    upcomingEvents: "Événements à venir",
    learnMore: "En savoir plus",
    storiesOfTransformation: "Histoires de transformation",
    stayUpdated: "Restez informé",
    subscribe: "S'abonner",
    multiDay: "Multi-jours",
    noFeaturedEvents: "Aucun événement vedette pour le moment. Revenez bientôt!",
    weRespectPrivacy: "Nous respectons votre vie privée. Désabonnez-vous à tout moment.",
    // Locations Page
    globalNetwork: "Réseau mondial",
    discoverSpiritualHome: "Découvrez votre foyer spirituel",
    locationHeroSubtitle: "Connectez-vous avec des communautés dynamiques à travers le monde. Trouvez des centres WCA et des foyers DCG où la foi, la communion et la transformation se produisent quotidiennement.",
    findYourCommunity: "Trouvez votre communauté",
    searchLocations: "Rechercher par nom, ville ou région...",
    allLocations: "Tous les emplacements",
    wcaCenters: "Centres WCA",
    dcgHomes: "Foyers DCG",
    allRegions: "Toutes les régions",
    clearFilters: "Effacer les filtres",
    locationsFound: "emplacements trouvés",
    noLocationsFound: "Aucun emplacement trouvé",
    dontSeeYourArea: "Vous ne voyez pas votre région?",
    startConversation: "Commencer la conversation",
    exploreEvents: "Explorer les événements",
    ourGlobalLocations: "Nos emplacements mondiaux",
    showingLocations: "Affichage de",
    ofLocations: "sur",
    weAreExpanding: "Nous élargissons notre réseau mondial chaque jour. Contactez-nous pour en savoir plus sur les prochains emplacements ou découvrez comment amener WCA dans votre communauté.",
    // Events Page
    eventsCalendar: "Calendrier des événements",
    upcomingWcaEvents: "Événements WCA à venir",
    searchEvents: "Rechercher des événements...",
    showFilters: "Afficher les filtres",
    hideFilters: "Masquer les filtres",
    noEventsFound: "Aucun événement trouvé",
    organizeEvent: "Organiser un événement avec WCA",
    organizeEventDesc: "Êtes-vous intéressé à organiser un événement WCA dans votre région? Nous fournissons des ressources et un soutien pour vous aider à organiser des rassemblements marquants pour votre communauté.",
    findALocation: "Trouver un emplacement",
    // Blog Page
    newsBlogTitle: "Actualités et blog",
    blogPageDesc: "Restez informé des dernières nouvelles, témoignages et articles de la World Changers Association.",
    all: "Tout",
    news: "Actualités",
    testimonies: "Témoignages",
    articles: "Articles",
    featuredPosts: "Articles en vedette",
    searchPosts: "Rechercher des articles...",
    readMore: "Lire la suite",
    comments: "commentaires",
    // Counseling Page
    counselingServices: "Services de conseil",
    counselingDesc: "Notre équipe de conseillers agréés et de personnel pastoral est là pour fournir des conseils, un soutien et une sagesse biblique pour les défis de la vie.",
    searchCounselors: "Rechercher des conseillers...",
    allSpecialties: "Toutes les spécialités",
    allDays: "Tous les jours",
    viewProfileSchedule: "Voir le profil et l'horaire",
    counselorProfile: "Profil du conseiller",
    specialties: "Spécialités",
    languagesSpoken: "Langues",
    experience: "Expérience",
    about: "À propos",
    selectTimeSlot: "Sélectionner un créneau horaire",
    scheduleAppointment: "Planifier un rendez-vous",
    requestAppointment: "Demander un rendez-vous",
    // Fundraising Page
    fundraisingProjects: "Projets de collecte de fonds",
    fundraisingDesc: "Rejoignez-nous pour faire la différence grâce à ces initiatives importantes qui transforment des vies et des communautés.",
    searchProjects: "Rechercher des projets...",
    allCategories: "Toutes les catégories",
    allProjects: "Tous les projets",
    active: "Actif",
    goalAmount: "Objectif",
    raised: "Collecté",
    supporters: "Supporters",
    startDate: "Date de début",
    endDate: "Date de fin",
    donate: "Faire un don",
    donateNow: "Faire un don maintenant",
    projectUpdates: "Mises à jour du projet",
    selectAmount: "Sélectionner le montant",
    customAmount: "Montant personnalisé",
    // Media Page
    mediaAndSermons: "Médias et sermons",
    mediaDesc: "Accédez à notre bibliothèque de sermons, d'enregistrements d'événements et d'enseignements pour grandir dans votre parcours spirituel.",
    sermons: "Sermons",
    category: "Catégorie",
    // Store Page
    wcaStore: "Boutique WCA",
    library: "Bibliothèque",
    storeDesc: "Parcourez notre collection de livres, de cours et de marchandises pour soutenir votre parcours spirituel.",
    libraryDesc: "Empruntez des ressources de notre vaste bibliothèque pour enrichir vos connaissances et votre croissance.",
    featuredCollection: "Collection en vedette",
    newArrivals: "Nouveautés",
    bestseller: "Best-seller",
    addToCart: "Ajouter au panier",
    filters: "Filtres",
    categories: "Catégories",
    type: "Type",
    book: "Livre",
    merchandise: "Marchandise",
    audio: "Audio",
    course: "Cours",
    // Already Enrolled (Duplicate Visitor/Member)
    welcomeBack: "Bienvenue!",
    alreadyRegisteredAsVisitor: "Vous êtes déjà inscrit en tant que visiteur dans cette région. Pas besoin de vous réinscrire!",
    alreadyRegisteredAsMember: "Vous êtes déjà inscrit en tant que membre dans cette région. Pas besoin de vous inscrire comme visiteur!",
    alreadyRegisteredMessage: "Vous êtes déjà inscrit dans cette région.",
    yourMemberId: "Votre identifiant de membre",
    goToHomepage: "Aller à la page d'accueil",
    tryDifferentEmail: "Essayer un autre e-mail",
    // Special Event Pre-Registration
    sr_badge: "Pré-inscription à un événement spécial",
    sr_step_you: "Vous",
    sr_step_onboard: "Inscription",
    sr_step_family: "Famille",
    sr_step_extras: "Extras",
    sr_identify_title: "Qui s'inscrit ?",
    sr_identify_desc: "Saisissez l'e-mail ou le numéro de téléphone utilisé lors de votre inscription à WCA. Si vous êtes nouveau, nous vous inscrirons ici-même.",
    sr_email: "E-mail",
    sr_telephone: "Téléphone",
    sr_email_placeholder: "vous@exemple.com",
    sr_phone_placeholder: "Numéro de téléphone",
    sr_check: "Vérifier",
    sr_hello_prefix: "Bonjour",
    sr_hello_middle: ", vous inscrivez-vous à",
    sr_hello_suffix: "en famille ou à titre individuel ?",
    sr_individual: "Individuel",
    sr_family_mode: "Famille",
    sr_not_in_system: "Vous n'êtes pas encore dans le système. Cliquez sur",
    sr_not_in_system_cta: "Continuer",
    sr_not_in_system_tail: "pour vous enregistrer et finaliser votre inscription.",
    sr_onboard_select_type_title: "Sélectionnez le type de participant à inscrire ci-dessous.",
    sr_onboard_select_type_desc: "Choisissez l'option qui correspond le mieux à cette personne.",
    sr_member_type: "Membre",
    sr_visitor_type: "Visiteur",
    sr_region_section: "Région WCA",
    sr_region_label: "Région",
    sr_region_placeholder: "Sélectionnez votre région",
    sr_region_help: "La région WCA à laquelle vous appartenez ou souhaitez être associé.",
    sr_personal_info: "Informations personnelles",
    sr_family_name: "Nom de famille",
    sr_other_names: "Autres prénoms",
    sr_phone: "Téléphone",
    sr_phone_placeholder_full: "+33 6 12 34 56 78",
    sr_address: "Adresse",
    sr_address_placeholder: "Rue, Ville, Pays",
    sr_dob: "Date de naissance",
    sr_gender: "Sexe",
    sr_select_gender: "Sélectionnez le sexe",
    sr_male: "Masculin",
    sr_female: "Féminin",
    sr_occupation: "Profession",
    sr_select_occupation: "Sélectionnez la profession",
    sr_spiritual_info: "Informations spirituelles",
    sr_foundation_q: "Avez-vous terminé l'École des Fondements ?",
    sr_foundation_date: "Date de fin de l'École des Fondements",
    sr_baptized_q: "Êtes-vous baptisé(e) ?",
    sr_baptism_date: "Date de baptême",
    sr_select: "Sélectionner",
    sr_ministry_title: "Ministère et service",
    sr_ministry_desc: "Sélectionnez les ministères dans lesquels vous souhaitez servir.",
    sr_ministry_music: "Musique et louange",
    sr_ministry_teaching: "Enseignement et prédication",
    sr_ministry_youth: "Ministère de la jeunesse",
    sr_ministry_children: "Ministère des enfants",
    sr_ministry_hospitality: "Accueil",
    sr_ministry_media: "Médias et technologie",
    sr_ministry_admin: "Administration",
    sr_ministry_counseling: "Conseil pastoral",
    sr_ministry_prayer: "Ministère de prière",
    sr_ministry_outreach: "Évangélisation et action sociale",
    sr_dcg_title: "Destiny Care Group",
    sr_dcg_label: "Sélectionner un DCG",
    sr_dcg_select_placeholder: "Choisir un DCG",
    sr_dcg_select_region_first: "Sélectionnez d'abord une région",
    sr_family_rel_title: "Liens familiaux (facultatif)",
    sr_rel_type: "Type de lien",
    sr_select_rel: "Sélectionnez un lien",
    sr_related_members: "Membres liés",
    sr_search_members: "Rechercher des membres…",
    sr_no_members: "Aucun membre trouvé.",
    sr_add_rel: "Ajouter un lien",
    sr_n_selected: "sélectionné(s)",
    sr_referral_title: "Recommandation",
    sr_referral_q: "Comment avez-vous entendu parler de nous ?",
    sr_select_referral: "Sélectionnez la source",
    sr_referral_invited_by: "Invité(e) par quelqu'un",
    sr_referral_social_media: "Réseaux sociaux",
    sr_referral_website: "Site web",
    sr_referral_other: "Autre",
    sr_invited_by_members: "Membre(s) qui vous a/ont invité(e)",
    sr_relationship: "Lien",
    sr_which_platform: "Quelle plateforme ?",
    sr_select_platform: "Sélectionnez la plateforme",
    sr_platform_other: "Autre",
    sr_tell_more: "Dites-nous-en plus",
    sr_tell_more_placeholder: "Comment avez-vous entendu parler de nous ?",
    sr_interest_title: "Intérêt",
    sr_join_q: "Souhaitez-vous rejoindre le WCA ?",
    sr_yes: "Oui",
    sr_no: "Non",
    sr_undecided: "Indécis(e)",
    sr_rel_spouse: "Conjoint(e)",
    sr_rel_child: "Enfant",
    sr_rel_parent: "Parent",
    sr_rel_sibling: "Frère/Sœur",
    sr_rel_guardian: "Tuteur/Tutrice",
    sr_rel_other: "Autre",
    sr_family_section_title: "Famille et enfants",
    sr_family_section_desc: "Cochez les membres de la famille qui vous accompagnent. Vous pouvez aussi ajouter une nouvelle personne.",
    sr_your_family: "Votre famille",
    sr_child_badge: "enfant",
    sr_add_person: "Ajouter une personne",
    sr_no_family: "Aucune famille ajoutée — c'est très bien si vous venez seul(e).",
    sr_linked: "Lié",
    sr_dont_have_person: "Nous n'avons pas encore cette personne — inscrivez-la ici.",
    sr_lodging_title: "Hébergement",
    sr_lodging_desc: "Indiquez si vous avez besoin d'un hébergement organisé par les organisateurs.",
    sr_need_lodging: "J'ai besoin d'un hébergement fourni par les organisateurs",
    sr_days_attend: "Jours de votre présence",
    sr_health_title: "Allergies et problèmes de santé",
    sr_health_desc: "Indiquez toute allergie ou tout problème de santé que nous devrions prendre en compte.",
    sr_health_food: "Allergie alimentaire",
    sr_health_drug: "Allergie médicamenteuse",
    sr_health_asthma: "Asthme / Respiratoire",
    sr_health_diabetes: "Diabète",
    sr_health_hypertension: "Hypertension",
    sr_health_mobility: "Mobilité / Accessibilité",
    sr_health_other: "Autre santé/allergie",
    sr_other_health_placeholder: "Autres précisions sur la santé ou les allergies",
    sr_pledge_title: "Promesse de soutien",
    sr_pledge_desc: "Prenez un engagement financier pour soutenir l'organisation de l'événement. Nous reviendrons vers vous pour le suivi.",
    sr_fundraising_goal: "Objectif de collecte",
    sr_continue: "Continuer",
    sr_back: "Retour",
    sr_submitting: "Envoi en cours…",
    sr_confirm: "Confirmer l'inscription",
    sr_done_title: "Vous êtes inscrit(e) !",
    sr_done_body_prefix: "Merci de vous être inscrit(e) à",
    sr_done_body_suffix: ". Vous pouvez commencer à vous préparer à vivre un moment formidable avec le Seigneur.",
    sr_browse_other: "Voir d'autres événements",
    sr_event_unavailable_title: "Événement indisponible",
    sr_event_unavailable_desc: "Cet événement n'est pas ouvert à l'inscription spéciale.",
    sr_back_to_events: "Retour aux événements",
    sr_toast_success_prefix: "Inscription réussie de",
    sr_toast_success_suffix: "participant(s) !",
    sr_toast_error: "Impossible de finaliser l'inscription",

    // Public fundraising
    fr_title: "Projets de collecte de fonds",
    fr_subtitle: "Rejoignez-nous pour faire la différence à travers ces initiatives qui transforment des vies et des communautés.",
    fr_search: "Rechercher des projets...",
    fr_all_status: "Tous les projets",
    fr_status_active: "En cours",
    fr_status_completed: "Terminé",
    fr_status_upcoming: "À venir",
    fr_no_projects: "Aucun projet pour le moment. Revenez bientôt.",
    fr_details: "Détails",
    fr_donate: "Faire un don",
    fr_pledge: "Engagement",
    fr_progress: "Progression",
    fr_supporters: "Donateurs",
    fr_raised: "collectés",
    fr_goal: "Objectif",
    fr_about: "À propos du projet",
    fr_recent_supporters: "Soutiens récents",
    fr_no_supporters: "Soyez le premier à soutenir ce projet.",
    fr_anonymous: "Anonyme",
    fr_back: "Retour",
    fr_pledge_title: "Prendre un engagement",
    fr_donate_title: "Faire un don",
    fr_phone: "Numéro de téléphone",
    fr_proceed: "Continuer",
    fr_checking: "Vérification…",
    fr_greet_match: "Bonjour {name}, saisissez ci-dessous le montant de votre engagement puis confirmez.",
    fr_greet_match_donate: "Bonjour {name}, indiquez le montant que vous souhaitez verser maintenant.",
    fr_greet_new: "Remplissez le formulaire ci-dessous puis confirmez votre engagement.",
    fr_greet_new_donate: "Remplissez le formulaire ci-dessous pour effectuer votre don.",
    fr_family_name: "Nom de famille",
    fr_other_names: "Autres prénoms",
    fr_email: "E-mail",
    fr_amount: "Montant",
    fr_pledge_amount: "Montant de l'engagement",
    fr_note_optional: "Note (facultatif)",
    fr_confirm_pledge: "Confirmer l'engagement",
    fr_pay_now: "Payer maintenant",
    fr_anonymous_toggle: "Faire un don anonyme",
    fr_my_pledge: "Votre engagement",
    fr_pledged: "Promis",
    fr_redeemed: "Versé",
    fr_remaining: "Reste",
    fr_success_pledge: "Merci ! Votre engagement a été enregistré.",
    fr_success_donate: "Merci ! Votre don a été enregistré et est en attente de paiement.",
    fr_lookup_error: "Impossible de vérifier votre numéro. Réessayez.",
    fr_submit_error: "Une erreur est survenue. Veuillez réessayer.",
  },

};
