import React, { useState, useMemo } from "react";
import PeriodFilter, { PeriodFilters } from "@/components/admin/regional/dashboard/PeriodFilter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  CalendarDays, Search, Plus, MoreHorizontal, Edit, UserCheck, Eye, EyeOff,
  Link2, Copy, Trash2, Globe, Star, Layers, Target, TrendingUp, TrendingDown,
} from "lucide-react";
import { useGlobalEvents, useCreateGlobalEvent, useDeleteGlobalEvent, useUpdateGlobalEvent } from "@/hooks/useGlobalEvents";
import { useAllRegions } from "@/hooks/useAllRegions";
import { useGlobalAttendanceHistoryWithMemberTypes } from "@/hooks/useAttendance";
import { useToast } from "@/components/ui/use-toast";
import { format } from "date-fns";
import { formatDateRange, formatTimeRange } from "@/utils/dateUtils";
import { generateSlug } from "@/utils/slugUtils";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
  AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { GlobalAttendanceDialog } from "@/components/admin/super/events/GlobalAttendanceDialog";

const eventCategories = [
  'Conference', 'Worship', 'Revival', 'Outreach', 'Training', 'Workshop',
  'Community Service', 'Bible Study', 'Retreat', 'Seminar', 'DCG Meeting', 'Other'
] as const;

const eventSchema = z.object({
  name: z.string().min(3, "Event name must be at least 3 characters."),
  description: z.string().optional(),
  category: z.enum(eventCategories),
  start_date: z.string().min(1, "Please select a start date."),
  start_time: z.string().min(1, "Please provide a start time."),
  end_date: z.string().optional(),
  end_time: z.string().optional(),
  location_name: z.string().min(3, "Please provide a location."),
  address: z.string().optional(),
  capacity: z.coerce.number().positive().int().optional(),
  is_public: z.boolean().default(true),
  is_featured: z.boolean().default(false),
  is_special: z.boolean().default(false),
  requires_pre_registration: z.boolean().default(false),
  attendance_target: z.coerce.number().positive().int().optional(),
  slug: z.string().min(3).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Only lowercase letters, numbers, and hyphens allowed").optional().or(z.literal("")),
  registration_url: z.string().url("Please enter a valid URL.").optional().or(z.literal("")),
});

const SuperEvents: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [eventTypeFilter, setEventTypeFilter] = useState("all");
  const [regionFilter, setRegionFilter] = useState("all");
  const [periodFilters, setPeriodFilters] = useState<PeriodFilters>(() => {
    const now = new Date();
    const from = new Date(now.getFullYear() - 1, now.getMonth(), now.getDate());
    return { dateRange: { from, to: undefined }, quickDateRange: '1-year' };
  });
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [eventToEdit, setEventToEdit] = useState<any>(null);
  const [eventToDelete, setEventToDelete] = useState<string | null>(null);
  const [attendanceDialogOpen, setAttendanceDialogOpen] = useState(false);
  const [selectedEvent, setSelectedEvent] = useState<any>(null);
  const [autoGeneratedSlug, setAutoGeneratedSlug] = useState<string>('');
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);
  const { toast } = useToast();

  const { data: events, isLoading } = useGlobalEvents();
  const { data: attendanceData } = useGlobalAttendanceHistoryWithMemberTypes();
  const { data: regions } = useAllRegions();
  const createEvent = useCreateGlobalEvent();
  const updateEvent = useUpdateGlobalEvent();
  const deleteEvent = useDeleteGlobalEvent();

  const form = useForm<z.infer<typeof eventSchema>>({
    resolver: zodResolver(eventSchema),
    defaultValues: {
      name: "", description: "", start_date: "", start_time: "",
      end_date: "", end_time: "", location_name: "", address: "",
      is_public: true, is_featured: false, is_special: false, requires_pre_registration: false, slug: "", registration_url: "",
    },
  });
  const editForm = useForm<z.infer<typeof eventSchema>>({ resolver: zodResolver(eventSchema) });

  // Period-filtered events
  const periodFilteredEvents = useMemo(() => {
    if (!events) return [];
    return events.filter((e: any) => {
      if (!e?.start_datetime) return false;
      const d = new Date(e.start_datetime);
      if (isNaN(d.getTime())) return false;
      if (periodFilters.dateRange.from && d < periodFilters.dateRange.from) return false;
      if (periodFilters.dateRange.to) {
        const endOfDay = new Date(periodFilters.dateRange.to);
        endOfDay.setHours(23, 59, 59, 999);
        if (d > endOfDay) return false;
      }
      return true;
    });
  }, [events, periodFilters]);

  const filteredEvents = useMemo(() => {
    const now = new Date();
    return periodFilteredEvents.filter((event: any) => {
      const name = event?.name ?? '';
      const term = searchTerm.toLowerCase();
      const matchesSearch = !term ||
        name.toLowerCase().includes(term) ||
        (event.category && event.category.toLowerCase().includes(term)) ||
        (event.location_name && event.location_name.toLowerCase().includes(term)) ||
        (event.regions?.name && event.regions.name.toLowerCase().includes(term));
      if (!matchesSearch) return false;

      if (eventTypeFilter === 'regional' && (event.dcg_id || event.is_special)) return false;
      if (eventTypeFilter === 'dcg' && !event.dcg_id) return false;
      if (eventTypeFilter === 'special' && !event.is_special) return false;
      if (eventTypeFilter === 'global' && event.region_id) return false;

      if (regionFilter !== 'all' && event.region_id !== regionFilter) return false;

      return true;
    });
  }, [periodFilteredEvents, searchTerm, eventTypeFilter, regionFilter]);

  const getEventAttendance = (eventId: string): number => {
    if (!attendanceData) return 0;
    const matched = attendanceData.filter((a: any) => a.source_event_id === eventId);
    return matched.reduce((sum: number, a: any) => sum + a.total_present, 0);
  };

  // KPI analytics — mirror regional analytics math
  const analyticsData = useMemo(() => {
    const safeAttendance = attendanceData || [];
    const list = filteredEvents || [];

    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();
    const lastMonth = currentMonth === 0 ? 11 : currentMonth - 1;
    const lastMonthYear = currentMonth === 0 ? currentYear - 1 : currentYear;

    const regionalEvents = list.filter((e: any) => !e.dcg_id && !e.is_special);
    const dcgEvents = list.filter((e: any) => !!e.dcg_id);
    const specialEvents = list.filter((e: any) => !!e.is_special);

    const avgAttendance = (eventList: any[]) => {
      const ids = eventList.map(e => e.id);
      const matched = safeAttendance.filter((a: any) => a.source_event_id && ids.includes(a.source_event_id));
      return matched.length > 0 ? Math.round(matched.reduce((s: number, a: any) => s + a.total_present, 0) / matched.length) : 0;
    };

    const growth = (eventList: any[]) => {
      const ids = eventList.map(e => e.id);
      const thisM = safeAttendance.filter((a: any) => {
        const d = new Date(a.event_date);
        return d.getMonth() === currentMonth && d.getFullYear() === currentYear && a.source_event_id && ids.includes(a.source_event_id);
      });
      const lastM = safeAttendance.filter((a: any) => {
        const d = new Date(a.event_date);
        return d.getMonth() === lastMonth && d.getFullYear() === lastMonthYear && a.source_event_id && ids.includes(a.source_event_id);
      });
      const thisAvg = thisM.length > 0 ? thisM.reduce((s: number, a: any) => s + a.total_present, 0) / thisM.length : 0;
      const lastAvg = lastM.length > 0 ? lastM.reduce((s: number, a: any) => s + a.total_present, 0) / lastM.length : 0;
      return lastAvg > 0 ? Math.round(((thisAvg - lastAvg) / lastAvg) * 100) : 0;
    };

    const totalAttendees = list.reduce((sum, e: any) => sum + getEventAttendance(e.id), 0);
    const totalCapacity = regionalEvents.reduce((sum, e: any) => sum + (e.capacity || 0), 0);
    const attendanceTargetPct = totalCapacity > 0 ? Math.round((totalAttendees / totalCapacity) * 100) : 0;

    return {
      total: { count: list.length, avg: avgAttendance(list), growth: growth(list) },
      regional: { count: regionalEvents.length, avg: avgAttendance(regionalEvents), growth: growth(regionalEvents) },
      dcg: { count: dcgEvents.length, avg: avgAttendance(dcgEvents), growth: growth(dcgEvents) },
      special: { count: specialEvents.length, avg: avgAttendance(specialEvents), growth: growth(specialEvents) },
      target: { pct: attendanceTargetPct, totalAttendees, totalCapacity },
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filteredEvents, attendanceData]);

  const getAttendanceLink = (slugOrId: string) => `${window.location.origin}/attend/${slugOrId}`;
  const getEventPageLink = (slugOrId: string) => `${window.location.origin}/events/${slugOrId}`;

  const copyAttendanceLink = (event: any) => {
    const identifier = event.slug || event.id;
    navigator.clipboard.writeText(getAttendanceLink(identifier));
    toast({ title: "Link Copied", description: "Self-attendance link copied to clipboard." });
  };

  async function onSubmit(values: z.infer<typeof eventSchema>) {
    try {
      const start_datetime = new Date(`${values.start_date}T${values.start_time}`).toISOString();
      let end_datetime: string | null = null;
      if (values.end_date) {
        const endTime = values.end_time || values.start_time;
        end_datetime = new Date(`${values.end_date}T${endTime}`).toISOString();
      }
      let finalSlug = values.slug || generateSlug(values.name);
      const { data: existingEvent } = await supabase.from('events').select('slug').eq('slug', finalSlug).maybeSingle();
      if (existingEvent) finalSlug = `${finalSlug}-${Date.now().toString(36)}`;

      await createEvent.mutateAsync({
        name: values.name,
        slug: finalSlug,
        description: values.description || null,
        category: values.category as any,
        start_datetime,
        end_datetime,
        location_name: values.location_name,
        address: values.address || null,
        capacity: values.capacity || null,
        attendance_target: values.attendance_target || null,
        is_public: values.is_public,
        is_featured: values.is_featured,
        is_special: values.is_special,
        requires_pre_registration: values.is_special ? !!values.requires_pre_registration : false,
        registration_url: values.registration_url || null,
        status: 'Upcoming',
        region_id: null,
      });

      toast({ title: "Success", description: "Global event created successfully." });
      form.reset();
      setAutoGeneratedSlug('');
      setSlugManuallyEdited(false);
      setCreateDialogOpen(false);
    } catch (err: any) {
      toast({ title: "Error", description: err.message || "Could not create event.", variant: "destructive" });
    }
  }

  function openEditDialog(event: any) {
    setEventToEdit(event);
    const startDate = new Date(event.start_datetime);
    const endDate = event.end_datetime ? new Date(event.end_datetime) : null;
    setSlugManuallyEdited(true);
    editForm.reset({
      name: event.name,
      description: event.description || "",
      category: event.category || "Other",
      start_date: format(startDate, 'yyyy-MM-dd'),
      start_time: format(startDate, 'HH:mm'),
      end_date: endDate ? format(endDate, 'yyyy-MM-dd') : "",
      end_time: endDate ? format(endDate, 'HH:mm') : "",
      location_name: event.location_name || "",
      address: event.address || "",
      capacity: event.capacity || undefined,
      is_public: event.is_public,
      is_featured: event.is_featured,
      is_special: !!event.is_special,
      requires_pre_registration: !!event.requires_pre_registration,
      attendance_target: event.attendance_target || undefined,
      slug: event.slug || "",
      registration_url: event.registration_url || "",
    });
    setEditDialogOpen(true);
  }

  async function onEditSubmit(values: z.infer<typeof eventSchema>) {
    if (!eventToEdit) return;
    try {
      const start_datetime = new Date(`${values.start_date}T${values.start_time}`).toISOString();
      let end_datetime: string | null = null;
      if (values.end_date) {
        const endTime = values.end_time || values.start_time;
        end_datetime = new Date(`${values.end_date}T${endTime}`).toISOString();
      }
      const newSlug = values.slug || eventToEdit.slug;
      if (newSlug && eventToEdit.slug && newSlug !== eventToEdit.slug) {
        await supabase.from('event_slug_history').insert({ event_id: eventToEdit.id, old_slug: eventToEdit.slug });
      }
      await updateEvent.mutateAsync({
        id: eventToEdit.id,
        name: values.name,
        slug: newSlug,
        description: values.description || null,
        category: values.category as any,
        start_datetime,
        end_datetime,
        location_name: values.location_name,
        address: values.address || null,
        capacity: values.capacity || null,
        attendance_target: values.attendance_target || null,
        is_public: values.is_public,
        is_featured: values.is_featured,
        is_special: values.is_special,
        requires_pre_registration: values.is_special ? !!values.requires_pre_registration : false,
        registration_url: values.registration_url || null,
      });
      toast({ title: "Success", description: "Event updated successfully." });
      setEditDialogOpen(false);
      setEventToEdit(null);
      setSlugManuallyEdited(false);
    } catch (err: any) {
      toast({ title: "Error", description: err.message || "Could not update event.", variant: "destructive" });
    }
  }

  const handleDelete = (id: string) => {
    deleteEvent.mutate(id, {
      onSuccess: () => { toast({ title: "Success", description: "Event deleted." }); setEventToDelete(null); },
      onError: (err: any) => toast({ title: "Error", description: err.message, variant: "destructive" }),
    });
  };

  // ---- KPI card ----
  const renderKpi = (
    label: string,
    count: number | string,
    sub: string,
    growth: number | null,
    Icon: React.ComponentType<{ className?: string }>,
    iconColor: string,
    iconBg: string,
  ) => (
    <div className="rounded-2xl border border-border/40 bg-card/60 backdrop-blur-sm p-5">
      <div className="flex items-center gap-3 mb-3">
        <div className={`flex h-9 w-9 items-center justify-center rounded-xl ${iconBg} ${iconColor}`}>
          <Icon className="h-5 w-5" />
        </div>
        <span className="text-sm font-medium text-muted-foreground">{label}</span>
      </div>
      <p className="font-bold text-foreground text-base tabular-nums mt-1">{count}</p>
      <p className="text-xs text-muted-foreground mt-1">{sub}</p>
      {growth !== null && (
        <div className="mt-2">
          {growth !== 0 ? (
            <div className={`flex items-center gap-1 ${growth > 0 ? 'text-green-600' : 'text-red-600'}`}>
              {growth > 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
              <span className="text-xs font-medium">{growth > 0 ? '+' : ''}{growth}% avg attendance</span>
            </div>
          ) : (
            <span className="text-xs text-muted-foreground">0% growth</span>
          )}
        </div>
      )}
    </div>
  );

  // ---- Event form (reused for create + edit) ----
  const renderEventForm = (formInstance: any, onSubmitFn: any, isEdit = false) => (
    <Form {...formInstance}>
      <form onSubmit={formInstance.handleSubmit(onSubmitFn)} className="space-y-4 max-h-[65vh] overflow-auto p-1">
        <FormField control={formInstance.control} name="name" render={({ field }) => (
          <FormItem>
            <FormLabel>Event Name *</FormLabel>
            <FormControl><Input placeholder="e.g. Annual Global Conference" {...field} onChange={(e) => {
              field.onChange(e);
              if (!slugManuallyEdited) {
                const newSlug = generateSlug(e.target.value);
                setAutoGeneratedSlug(newSlug);
                formInstance.setValue('slug', newSlug);
              }
            }} /></FormControl>
            <FormMessage />
          </FormItem>
        )} />
        <FormField control={formInstance.control} name="slug" render={({ field }) => (
          <FormItem>
            <FormLabel>URL Slug</FormLabel>
            <FormControl><Input placeholder="e.g. annual-global-conference" {...field} value={field.value || ''} onChange={(e) => {
              const val = e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '');
              field.onChange(val);
              setSlugManuallyEdited(true);
            }} /></FormControl>
            <p className="text-xs text-muted-foreground">Used in Event Page and Attendance URLs.</p>
            <FormMessage />
          </FormItem>
        )} />
        {formInstance.watch('slug') && (
          <div className="space-y-2 rounded-md border p-3 bg-muted/50">
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Event Page URL</p>
              <div className="flex gap-2">
                <Input readOnly className="bg-muted text-sm" value={getEventPageLink(formInstance.watch('slug') || '')} />
                <Button type="button" variant="outline" size="icon" onClick={() => { navigator.clipboard.writeText(getEventPageLink(formInstance.watch('slug') || '')); toast({ title: "Copied" }); }}><Copy className="h-4 w-4" /></Button>
              </div>
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Attendance URL</p>
              <div className="flex gap-2">
                <Input readOnly className="bg-muted text-sm" value={getAttendanceLink(formInstance.watch('slug') || '')} />
                <Button type="button" variant="outline" size="icon" onClick={() => { navigator.clipboard.writeText(getAttendanceLink(formInstance.watch('slug') || '')); toast({ title: "Copied" }); }}><Copy className="h-4 w-4" /></Button>
              </div>
            </div>
          </div>
        )}
        <FormField control={formInstance.control} name="category" render={({ field }) => (
          <FormItem>
            <FormLabel>Category *</FormLabel>
            <Select onValueChange={field.onChange} value={field.value}>
              <FormControl><SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger></FormControl>
              <SelectContent>{eventCategories.map(cat => <SelectItem key={cat} value={cat}>{cat}</SelectItem>)}</SelectContent>
            </Select>
            <FormMessage />
          </FormItem>
        )} />
        <FormField control={formInstance.control} name="description" render={({ field }) => (
          <FormItem><FormLabel>Description</FormLabel><FormControl><Textarea placeholder="Event description..." {...field} /></FormControl><FormMessage /></FormItem>
        )} />
        <div className="grid grid-cols-2 gap-4">
          <FormField control={formInstance.control} name="start_date" render={({ field }) => (<FormItem><FormLabel>Start Date *</FormLabel><FormControl><Input type="date" {...field} /></FormControl><FormMessage /></FormItem>)} />
          <FormField control={formInstance.control} name="start_time" render={({ field }) => (<FormItem><FormLabel>Start Time *</FormLabel><FormControl><Input type="time" {...field} /></FormControl><FormMessage /></FormItem>)} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <FormField control={formInstance.control} name="end_date" render={({ field }) => (<FormItem><FormLabel>End Date</FormLabel><FormControl><Input type="date" {...field} /></FormControl><FormMessage /></FormItem>)} />
          <FormField control={formInstance.control} name="end_time" render={({ field }) => (<FormItem><FormLabel>End Time</FormLabel><FormControl><Input type="time" {...field} /></FormControl><FormMessage /></FormItem>)} />
        </div>
        <FormField control={formInstance.control} name="location_name" render={({ field }) => (<FormItem><FormLabel>Location *</FormLabel><FormControl><Input placeholder="e.g. Convention Center" {...field} /></FormControl><FormMessage /></FormItem>)} />
        <FormField control={formInstance.control} name="address" render={({ field }) => (<FormItem><FormLabel>Address</FormLabel><FormControl><Input placeholder="Full address..." {...field} /></FormControl><FormMessage /></FormItem>)} />
        <FormField control={formInstance.control} name="registration_url" render={({ field }) => (<FormItem><FormLabel>External Registration URL</FormLabel><FormControl><Input type="url" placeholder="https://example.com/register" {...field} /></FormControl><FormMessage /></FormItem>)} />
        <div className="grid grid-cols-2 gap-4">
          <FormField control={formInstance.control} name="capacity" render={({ field }) => (<FormItem><FormLabel>Capacity</FormLabel><FormControl><Input type="number" placeholder="Max attendees" {...field} /></FormControl><FormMessage /></FormItem>)} />
          <FormField control={formInstance.control} name="attendance_target" render={({ field }) => (<FormItem><FormLabel>Attendance Target</FormLabel><FormControl><Input type="number" placeholder="Target attendees" {...field} /></FormControl><FormMessage /></FormItem>)} />
        </div>
        <div className="flex items-center gap-6 flex-wrap">
          <FormField control={formInstance.control} name="is_public" render={({ field }) => (
            <FormItem className="flex items-center gap-2 space-y-0">
              <FormControl><input type="checkbox" checked={!!field.value} onChange={field.onChange} className="h-4 w-4 rounded border-input" /></FormControl>
              <FormLabel className="font-normal">Public Event</FormLabel>
            </FormItem>
          )} />
          <FormField control={formInstance.control} name="is_featured" render={({ field }) => (
            <FormItem className="flex items-center gap-2 space-y-0">
              <FormControl><input type="checkbox" checked={!!field.value} onChange={field.onChange} className="h-4 w-4 rounded border-input" /></FormControl>
              <FormLabel className="font-normal">Featured</FormLabel>
            </FormItem>
          )} />
          <FormField control={formInstance.control} name="is_special" render={({ field }) => (
            <FormItem className="flex items-center gap-2 space-y-0">
              <FormControl><input type="checkbox" checked={!!field.value} onChange={field.onChange} className="h-4 w-4 rounded border-input" /></FormControl>
              <FormLabel className="font-normal">Special Event</FormLabel>
            </FormItem>
          )} />
          {formInstance.watch('is_special') && (
            <FormField control={formInstance.control} name="requires_pre_registration" render={({ field }) => (
              <FormItem className="flex items-center gap-2 space-y-0">
                <FormControl><input type="checkbox" checked={!!field.value} onChange={field.onChange} className="h-4 w-4 rounded border-input" /></FormControl>
                <FormLabel className="font-normal">Requires Pre-Registration</FormLabel>
              </FormItem>
            )} />
          )}
        </div>
        <DialogFooter>
          <Button type="submit" disabled={createEvent.isPending || updateEvent.isPending}>
            {(createEvent.isPending || updateEvent.isPending) ? "Saving..." : isEdit ? "Update Event" : "Create Event"}
          </Button>
        </DialogFooter>
      </form>
    </Form>
  );

  const renderTypeBadge = (event: any) => {
    if (event.is_special) return <Badge className="bg-amber-500/15 text-amber-700 hover:bg-amber-500/20 border-amber-500/30">Special</Badge>;
    if (event.dcg_id) return <Badge className="bg-purple-500/15 text-purple-700 hover:bg-purple-500/20 border-purple-500/30">DCG</Badge>;
    if (!event.region_id) return <Badge className="bg-primary/15 text-primary border-primary/30"><Globe className="h-3 w-3 mr-1" />Global</Badge>;
    return <Badge variant="secondary">Regional</Badge>;
  };

  return (
    <div className="space-y-6">
      {/* Period + filters row */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
        <PeriodFilter
          filters={periodFilters}
          onFiltersChange={(p) => setPeriodFilters(prev => ({ ...prev, ...p }))}
          className="mb-0"
        />
        <div className="flex flex-wrap items-center gap-2">
          <div className="relative">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input placeholder="Search events..." className="pl-8 w-[220px]" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
          </div>
          <Select value={eventTypeFilter} onValueChange={setEventTypeFilter}>
            <SelectTrigger className="w-[140px]"><SelectValue placeholder="All Types" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Types</SelectItem>
              <SelectItem value="regional">Regional</SelectItem>
              <SelectItem value="dcg">DCG</SelectItem>
              <SelectItem value="special">Special</SelectItem>
              <SelectItem value="global">Global</SelectItem>
            </SelectContent>
          </Select>
          <Select value={regionFilter} onValueChange={setRegionFilter}>
            <SelectTrigger className="w-[180px]"><SelectValue placeholder="All Regions" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Regions</SelectItem>
              {(regions || []).map((r: any) => (
                <SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button onClick={() => setCreateDialogOpen(true)}><Plus className="mr-2 h-4 w-4" />Add Event</Button>
        </div>
      </div>

      {/* KPI cards (5) */}
      <div className="grid gap-4 md:grid-cols-5">
        {renderKpi('Total Events', analyticsData.total.count, `Avg: ${analyticsData.total.avg} attendees`, analyticsData.total.growth, CalendarDays, 'text-primary', 'bg-primary/10')}
        {renderKpi('Regional Events', analyticsData.regional.count, `Avg: ${analyticsData.regional.avg} attendees`, analyticsData.regional.growth, Layers, 'text-primary', 'bg-primary/10')}
        {renderKpi('DCG Events', analyticsData.dcg.count, `Avg: ${analyticsData.dcg.avg} attendees`, analyticsData.dcg.growth, UserCheck, 'text-purple-600', 'bg-purple-500/10')}
        {renderKpi('Special Events', analyticsData.special.count, `Avg: ${analyticsData.special.avg} attendees`, analyticsData.special.growth, Star, 'text-amber-600', 'bg-amber-500/10')}
        {renderKpi('Attendance Target', `${analyticsData.target.pct}%`, `${analyticsData.target.totalAttendees} of ${analyticsData.target.totalCapacity} capacity`, null, Target, 'text-emerald-600', 'bg-emerald-500/10')}
      </div>

      {/* Events table */}
      <div className="rounded-2xl border border-border/40 bg-card/60 backdrop-blur-sm">
        <div className="p-5 border-b border-border/40 flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary">
            <CalendarDays className="h-5 w-5" />
          </div>
          <div>
            <h3 className="font-semibold">Events</h3>
            <p className="text-sm text-muted-foreground">View and manage events across all WCA regions.</p>
          </div>
        </div>
        <div className="p-2 overflow-x-auto">
          {isLoading ? (
            <div className="p-4 space-y-2">{Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-12 w-full" />)}</div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Event Name</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Time</TableHead>
                  <TableHead>Location</TableHead>
                  <TableHead>Region</TableHead>
                  <TableHead className="text-right">Capacity</TableHead>
                  <TableHead className="text-right">Attendance</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredEvents.length === 0 ? (
                  <TableRow><TableCell colSpan={9} className="text-center py-10 text-muted-foreground">No events found for the selected filters.</TableCell></TableRow>
                ) : filteredEvents.map((event: any) => (
                  <TableRow key={event.id}>
                    <TableCell>
                      <div className="font-medium">{event.name}</div>
                      <div className="flex items-center gap-1 mt-1">
                        {event.is_public ? <Eye className="h-3 w-3 text-muted-foreground" /> : <EyeOff className="h-3 w-3 text-muted-foreground" />}
                        <span className="text-xs text-muted-foreground">{event.is_public ? 'Public' : 'Private'}</span>
                      </div>
                    </TableCell>
                    <TableCell>{renderTypeBadge(event)}</TableCell>
                    <TableCell className="text-sm">{formatDateRange(event.start_datetime, event.end_datetime)}</TableCell>
                    <TableCell className="text-sm">{formatTimeRange(event.start_datetime, event.end_datetime)}</TableCell>
                    <TableCell className="text-sm">{event.location_name || 'TBD'}</TableCell>
                    <TableCell className="text-sm">
                      {event.region_id ? (event.regions?.name || 'Regional') : <span className="inline-flex items-center gap-1 text-primary"><Globe className="h-3 w-3" />Global</span>}
                    </TableCell>
                    <TableCell className="text-right text-sm">{event.capacity ?? 'N/A'}</TableCell>
                    <TableCell className="text-right text-sm font-medium">{getEventAttendance(event.id)}</TableCell>
                    <TableCell className="text-right">
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild><Button variant="ghost" size="sm"><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem onClick={() => openEditDialog(event)}><Edit className="mr-2 h-4 w-4" />Edit</DropdownMenuItem>
                          <DropdownMenuItem onClick={() => { setSelectedEvent(event); setAttendanceDialogOpen(true); }}><UserCheck className="mr-2 h-4 w-4" />Mark Attendance</DropdownMenuItem>
                          <DropdownMenuItem onClick={() => copyAttendanceLink(event)}><Link2 className="mr-2 h-4 w-4" />Copy Attendance Link</DropdownMenuItem>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem className="text-destructive" onClick={() => setEventToDelete(event.id)}><Trash2 className="mr-2 h-4 w-4" />Delete</DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </div>
      </div>

      {/* Create Event Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Create Global Event</DialogTitle>
            <DialogDescription>Create an inter-regional event visible across all regions.</DialogDescription>
          </DialogHeader>
          {renderEventForm(form, onSubmit)}
        </DialogContent>
      </Dialog>

      {/* Edit Event Dialog */}
      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Edit Event</DialogTitle>
            <DialogDescription>Update event details.</DialogDescription>
          </DialogHeader>
          {renderEventForm(editForm, onEditSubmit, true)}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={!!eventToDelete} onOpenChange={() => setEventToDelete(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Event</AlertDialogTitle>
            <AlertDialogDescription>This permanently deletes this event and all associated attendance records.</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={() => eventToDelete && handleDelete(eventToDelete)} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">Delete</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Attendance Dialog */}
      {selectedEvent && (
        <GlobalAttendanceDialog
          isOpen={attendanceDialogOpen}
          onClose={() => { setAttendanceDialogOpen(false); setSelectedEvent(null); }}
          event={selectedEvent}
        />
      )}
    </div>
  );
};

export default SuperEvents;
